### ISSUE TITLE
Italian translations

### ISSUE THREAD

**Issue by digitalplayer-steemit** [cyclosproject/cyclos4-ui#1]
Hello 

I would like to contribute with Italian translations.

I can do that only using Github as I am an adopter of Utopian.io project to reward open source software.

Just let me know if you are interested and I will be there for it

Best Regards
Michael Asumcinei
steemit.com/@digitalplayer

**Comment by luisfpg** [comment]
@digitalplayer-steemit Thanks for your interest.
This project is still in a very early stage of development.
Once we reach a milestone that we can start translations, I'll let you know.

**Comment by bingy92** [comment]
hello,

I just tried to install on ubuntu 16 and got this error:
------------------------------------------------------------------------------
cat /root/.npm/_logs/2018-05-13T07_44_25_365Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle cyclos4-ui@0.1.0~prebuild: cyclos4-ui@0.1.0
6 info lifecycle cyclos4-ui@0.1.0~build: cyclos4-ui@0.1.0
7 verbose lifecycle cyclos4-ui@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle cyclos4-ui@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/cyclos4-ui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle cyclos4-ui@0.1.0~build: CWD: /usr/src/cyclos4-ui
10 silly lifecycle cyclos4-ui@0.1.0~build: Args: [ '-c',
10 silly lifecycle   'ng-swagger-gen && ng-translation-gen && ng build -prod' ]
11 silly lifecycle cyclos4-ui@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle cyclos4-ui@0.1.0~build: Failed to exec build script
13 verbose stack Error: cyclos4-ui@0.1.0 build: `ng-swagger-gen && ng-translation-gen && ng build -prod`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cyclos4-ui@0.1.0
15 verbose cwd /usr/src/cyclos4-ui
16 verbose Linux 4.4.0-124-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.11.1
---------------------------------------------------------------------------

Can you assist to fix please?

**Comment by luisfpg** [comment]
@digitalplayer-steemit If you are still interested in translating the application to Italian, we now are in shape to release the frontend shortly.
Just follow https://github.com/cyclosproject/cyclos4-ui#translating
I'm closing this issue for now.
