### ISSUE TITLE
Don't show the keywords field on search users if not enabled

### ISSUE THREAD

**Issue by rleonuy** [cyclosproject/cyclos4-ui#102]
It does not bring any results, also the keyword filter is not visible in the main web public search.
![ui-search](https://user-images.githubusercontent.com/50959077/59451377-bb3ce900-8de1-11e9-833e-da029dfcde22.png)
![web-search](https://user-images.githubusercontent.com/50959077/59451378-bb3ce900-8de1-11e9-8f55-aafd038e461b.png)

**Comment by luisfpg** [comment]
We should use the `allowKeywords` property in user data for search to determine whether the field is visible
