### ISSUE TITLE
Problems when changing expired password

### ISSUE THREAD

**Issue by rleonuy** [cyclosproject/cyclos4-ui#107]
After login, the expired password form appears, but it won't enable the submit button until 30~ seconds or more, although the fields has already been filled.
Also, if I want to logout the page just keeps reloading and cannot leave it.

![error](https://user-images.githubusercontent.com/50959077/59511003-884f2f80-8e8b-11e9-9330-256598b0e585.png)

**Comment by andresmq** [comment]
Please check also this #95
