### ISSUE TITLE
Cannot add a contact as broker only

### ISSUE THREAD

**Issue by rleonuy** [cyclosproject/cyclos4-ui#108]
The autocomplete field does not retrieve any results. The same operation is working in main web.
If I try to submit it says that the field is required (which is a bit confusing), also the red cross doesn't clear the entered value.
![errorui](https://user-images.githubusercontent.com/50959077/59511918-ef6de380-8e8d-11e9-95e1-c10f7d37ef33.png)
![web](https://user-images.githubusercontent.com/50959077/59511987-17f5dd80-8e8e-11e9-9f6b-211168986948.png)

**Comment by luisfpg** [comment]
Actually, won't show the add contact button if the logged user can't search for other users
