### ISSUE TITLE
Access child configuration URLs in 4UI

### ISSUE THREAD

**Issue by atitokor** [cyclosproject/cyclos4-ui#111]
Question: I have a single cyclos default network at cyclos.example.com and two child configurations that point to cyclos.example.com/country1 and cyclos.example.com/country2. Using CORS with 4UI users can access our service at www.example.com which points to Configuration.apiRoot = 'https://cyclos.example.com/api'; in setup.ts. Now my question is, can I get my country1 and country2 users to access our services at www.example.com/country1 and www.example.com/country2 through the same API? If so how, and if not, what other options do I have?

**Comment by luisfpg** [comment]
There's an option in the Configuration, in the Restrictions section called Allow access.
By default you can access by your URL, plus any ancestor.
So, if you setup the frontend's rootUrl to www.example.com, all users will access from there, no 
problems. This is the easiest option.
If you set it to www.example.com/country1, then only users with the country1 network will access (can be changed in config).
The other alternative is to deploy different frontend setups, one per country.

**Comment by atitokor** [comment]
Thanks! That answers our question. We highly appreciate your attention.

Art
