### ISSUE TITLE
Can not confirm operations if the channel is configured with device or password but the user doesn't have an active password

### ISSUE THREAD

**Issue by andresmq** [cyclosproject/cyclos4-ui#146]
Eg. in a payment, when confirming, the notification message "In order to confirm, scan this QR-code with your mobile phone" is shown but not the the qr-code.
![no-qr](https://user-images.githubusercontent.com/26793400/60597447-54c43e80-9d81-11e9-97a4-62f3f5824a60.png)

**Comment by agonzalezcy** [comment]
May be it can fix cheking by "device === AvailabilityEnum.REQUIRED || device === AvailabilityEnum.OPTIONAL" in auth-helper.service.ts.canConfirm():94
