### ISSUE TITLE
The RedeemVouchers permission for operator group does not hide/view control the Banking->Redeem menu

### ISSUE THREAD

**Issue by agonzalezcy** [cyclosproject/cyclos4-ui#153]
An operator from group which does not have RedeemVouchers permission, can see the Banking->RedeemVoucher menu option, but if the operator try access get a PermissionDenied. 

We should hide the RedeemVoucher menu option if the loged user is a restricted operator and does not have the RedeemVoucher group permission (same problem with Banking->ViewReddems menu option)

**Comment by tecnomada** [comment]
It was tested and it cannot be reproduced.
