### ISSUE TITLE
Question About this App's Reliability

### ISSUE THREAD

**Issue by EdwinM96** [cyclosproject/cyclos4-ui#18]
Hello from Puntotransacciones

I have a question about this app's reliability regarding if it's safe enought to use in a production environment, or if we have to absolutely wait for its official release. 

I know this isn't the best place to ask something like this, but due to not having a direct channel of communication with Mr. Luis I'm recuring to this method of communication.

**Comment by luisfpg** [comment]
While the cyclos4-ui application hasn't been officially released, it should be stable enough.
Of course, it is recommended that you install it in a server, and test all flows that will be needed by your customers. If you find any bugs, let us know.
The set of implemented functionality is described here https://github.com/cyclosproject/cyclos4-ui#implemented-functionality. More functionality will be added in future versions.

**Comment by EdwinM96** [comment]
Thanks for your reply Mr. Luis. And about the initial configuration: Is there any configuration needed prior to testing the application? 
I tried deploying the application on github's repo services (without doing any changes to the project) on the following URL:
https://edwinm96.github.io/Cyclos4-ui-integration/

But I get the following errors on the browser console:
![image](https://user-images.githubusercontent.com/37345191/55743053-9053a480-59ee-11e9-8bbd-188f5772db14.png)

And about a small issue I've found:
There is certain content that disappear (actually they aren't generated) when navigating the app's pages throught the browser's back and forth keys.
 For example the advertisement and banner space on the "Advertisments" page disappears when going back and forth between a page that does not contain advertisement:

![image](https://user-images.githubusercontent.com/37345191/55743622-03a9e600-59f0-11e9-9a29-54039b6588ff.png)

![image](https://user-images.githubusercontent.com/37345191/55743533-cd6c6680-59ef-11e9-91c5-33b60da33b51.png)

I guess this isn't the app's intended navigation flow, and its very likely an issue due to Angular's way of managing URL's. This is just maybe something to keep in mind for future features, where a user can perform a more complex and nested task.

**Comment by luisfpg** [comment]
Regarding the app not running in that deploy, it doesn't seem to have a backend running on https://edwinm96.github.io/Cyclos4-ui-integration/api.

Regarding not showing banners when hitting back, we'll investigate later on. Please, create a new issue for that matter, so I'll leave it open with bug status. This one I'm closing as question.

**Comment by EdwinM96** [comment]
Thank you Mr. Luis
