### ISSUE TITLE
Mixed content warnings because images are referenced using HTTP scheme

### ISSUE THREAD

**Issue by cmeury** [cyclosproject/cyclos4-ui#240]
I'm trying to serve the UI via HTTPS only, but get mixed content warnings because images are referenced with HTTP in the HTML. I could not find a way to configure that images are being served with HTTPS scheme. 

Example: `http://DOMAIN.TLD/content/images/currentConfiguration/SYSTEM_LOGO`

### Environment
* Docker container
* Cyclos version: 4.12.3
* Cyclos revision: bdfb8eba0ab6d38c6bc83ec27e2ba6a59fba7d2a

**Comment by luisfpg** [comment]
This URL seems to be generated from Cyclos itself, not the frontend.
What is the root URL you have in the Cyclos configuration?
Make sure to determine the same configuration as used in the frontend

**Comment by cmeury** [comment]
I have the "Main URL" in both global and network configuration set to the same HTTPS URL. I honestly have no idea how to access the "cyclos configuration" itself.

**Comment by cmeury** [comment]
I've closed the prototype phase without solving this issue, so I'm going to close it here.

**Comment by luisfpg** [comment]
@cmeury Cyclos itself is not free software. This one is a new frontend which is FLOSS, but the backend is not.

**Comment by cmeury** [comment]
Ohhh, okay, I did not realize! Thanks for letting me know.
