### ISSUE TITLE
Problem when displaying the full image in gallery

### ISSUE THREAD

**Issue by rleonuy** [cyclosproject/cyclos4-ui#246]
When creating an ad, or registering a new user, after upload a second image and click on it to display in full size, the spinner is displaying in the right part of the screen, see screenshot. (It happens in test.cyclos.org because things goes slowly, it does not happen in local environment)

**Comment by rleonuy** [comment]
![image-gallery](https://user-images.githubusercontent.com/50959077/71676456-0ce99880-2d5f-11ea-8124-44d037e7076b.png)

**Comment by luisfpg** [comment]
Couldn't find an easy fix.
We'll later on investigate switching to https://murhafsousli.github.io/ngx-gallery instead of ngx-lightbox.

**Comment by luisfpg** [comment]
No longer happens after we switched to ngx-gallery.
