### ISSUE TITLE
Wrong calendar layout in 320x480

### ISSUE THREAD

**Issue by agonzalezcy** [cyclosproject/cyclos4-ui#266]
Famoco has a 320x480 screen an if you access to Personal->MyProfile->Edit->Birthday and click on calendar Icon, then all screen is grayed and do not see the calendar.

We can reproduce it in responsive mode on chrome working with a fresh develop db

**Comment by luisfpg** [comment]
This issue was fixed by using a native `<input type="date">` for xxs and xs.
