### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by britishmtc** [cyclosproject/cyclos4-ui#27]
Hello

I try  install the cyclos4-ui and I do step by step as show in the code and I try access it on the localhost:4200 show like offline and I try all way as in the installation guide but I failed

and honestly I am very existing and interesting to install it on my server but I failed and I am looking for some help and how can help me to solve the installation

can kindly some one help in installation and configuration

Regards
Baligh

**Comment by luisfpg** [comment]
This is because the frontend can't connect to a Cyclos backend.
You should edit the `proxy.json` file to point to your Cyclos backend.
I've added a notice in https://github.com/cyclosproject/cyclos4-ui#debugging

**Comment by britishmtc** [comment]
Hello Luis and thank you for your help and support

The backend of my cyclos access is http://138.68.66.99:8080/cyclos/global/
and I see the http://localhost:8888

So I should replace this localhost lin with my existing backend link for my cyclos

I try all way and I set the backend but still not runing anf not working

there is a way can you support us and try solve it please and I appreciate it in advance

Regards
Baligh

**Comment by luisfpg** [comment]
You should normally replace the `/global` by your network internal name. If your network is marked as default, you don't need any suffix.
It is basically the URL that users would use, appended with `/api`

**Comment by britishmtc** [comment]
hmmm
honestly not clear the answer to me special what do you mean the URL that users would use appended with /api

can you be more clear please how exactly should be set the link and what configuration exactly should be made from my side

also can you support me and I will pay for that support?

I appreciate your help and support and thanks in advance for your reply and help

Regards
Baligh

**Comment by EdwinM96** [comment]
To get things going, you just have to do the folowing:
1. Download and prepare the project's dependencies throught NPM. (It is worth it to download Angular CLI too, so you can see changes live. Also make sure you have all the requirements first)
https://github.com/cyclosproject/cyclos4-ui#requirements
https://github.com/cyclosproject/cyclos4-ui#getting-and-preparing-the-code

2. Run `NG Build` on your project
3. Change 'setup.ts', as described on https://github.com/cyclosproject/cyclos4-ui#basic-setup. The api URL is the only change you need to make to see a live version of the proyect in your pc.
4. Run `NG serve -o`
