### ISSUE TITLE
Personal settings not translating correctly to spanish

### ISSUE THREAD

**Issue by EdwinM96** [cyclosproject/cyclos4-ui#28]
The settings for the theme appear to have no translation assigned in Spanish.

This is its appearance:
![image](https://user-images.githubusercontent.com/37345191/58126801-02fc9600-7bd1-11e9-9a5b-8d4190d5d5c4.png)

**Comment by luisfpg** [comment]
There is no way to disable the settings page.
Actually, any newly added functionality may have some delay until all translations are finished.
That said, the current version does have these Spanish translations.
Can you, please, check again?

**Comment by EdwinM96** [comment]
Yes, you are right. I redownloaded the project and tried running it to find out that the translation is fine. Perhaps it was something I did to the previous that caused this behavior.

**Comment by luisfpg** [comment]
The idea is to add more settings on the next versions.
