### ISSUE TITLE
Content page resolver script

### ISSUE THREAD

**Issue by tchetagni** [cyclosproject/cyclos4-ui#284]
Hi,
Using content page resolver, How to do inject typescript in requested external page?
Thanks

**Comment by luisfpg** [comment]
You can't inject TypeScript on an external page. TypeScript is compiled to JavaScript, which is what runs on the browser.
What are you trying to achieve?

**Comment by tchetagni** [comment]
I want to add a custom view(in typescript), in banking menu.
How to add an angular view component in cyclos-ui architecture?

**Comment by luisfpg** [comment]
If it is a (static) content page you can just use a [content page](https://github.com/cyclosproject/cyclos4-ui#customizing-content).
If it is a dynamic page, with actual angular components, then you need to program it as usual in Angular (component added to the `BankingModule`), with a view, etc. You'll have to make your component inherit one of the [base page classes](https://github.com/cyclosproject/cyclos4-ui/wiki/Base-component-hierarchy), add a menu for it in the `Menu` module `menu.ts` and customize the `menu.service.ts` to enable that menu item.
Sorry, I can't give a detailed walk through, but there are plenty of examples of other pages.

**Comment by tchetagni** [comment]
thank you
