### ISSUE TITLE
Remove @agm/core and do the map handling by hand

### ISSUE THREAD

**Issue by luisfpg** [cyclosproject/cyclos4-ui#299]
There's a huge difference in performance.
We should manually manage the map and the marker to avoid this overhead.

**Comment by acaurrinhos** [comment]
Have a look on the marker using the dark theme.

![Seleção_181](https://user-images.githubusercontent.com/55256310/77759835-2aec2f80-7014-11ea-8afd-1c833b00d75f.png)
