### ISSUE TITLE
Edit Profile page not displaying properly

### ISSUE THREAD

**Issue by EdwinM96** [cyclosproject/cyclos4-ui#31]
I just downloaded a plain new copy of the project and only changed the api url so that the content would display, and I get the following page when clicking on "Edit" button  on my profile.

![image](https://user-images.githubusercontent.com/37345191/58192026-12d1b400-7c7d-11e9-8f9d-4978e993b26a.png)

The live demo does not seem to display the profile content this way. Could this issue be related to the personalized fields added to the user profile on the Cyclos server?

**Comment by luisfpg** [comment]
It is probably a bug related to some configuration.
Can you, please, run it in development, capture the error in the browser console (F12) and attach it here?

**Comment by EdwinM96** [comment]
Sure, this are the console errors I'm getting:

![image](https://user-images.githubusercontent.com/37345191/58335246-628bb900-7dfe-11e9-800e-a67307f7d559.png)

**Comment by EdwinM96** [comment]
Yes 'email2' is a custom field.
![image](https://user-images.githubusercontent.com/37345191/58715176-8ceff000-8383-11e9-8520-3b5626e08acc.png)

Here is an image of an user with no custom fields.
![image](https://user-images.githubusercontent.com/37345191/58715404-0556b100-8384-11e9-8959-37cf1b930747.png)

It displays its info just fine.

**Comment by luisfpg** [comment]
We were never able to reproduce. Can you, please, check it with the current master code, which will be soon released as 1.1?

**Comment by EdwinM96** [comment]
Yes, its working now
