### ISSUE TITLE
Change the spinner to Bootstrap's built-in spinner and use it in buttons

### ISSUE THREAD

**Issue by luisfpg** [cyclosproject/cyclos4-ui#322]
When we started using Bootstrap it still didn't have any spinner, so we created one our own.
Now we need to show the spinner inside buttons, such as:

- User registration
- Login
- Payment
- ...

And the spinner we have doesn't scale well to small sizes. We've already used it small in the receive QR payment, but it didn't look so nice.

So, we should replace the spinner with Bootstrap's one, and show it in those buttons.

Here is the documentation for Bootstrap's spinner: https://getbootstrap.com/docs/4.4/components/spinners

**Comment by luisfpg** [comment]
The solution is to create a new component <action-button>.
It will have the following:

- `@Input() kind`="primary" | "outline" to generate the correct classes (primary by default)
- `@Input() label` to set the button label
- `@Input() disabled` to set the button disabled state
- `@Output() click`to emit the regular click event

Besides the label, the button can also show a bootstrap spinner. We will show it if the following matches: `disabled && (requesting$ | async)`. That `requesting$` Observable is in BaseComponent.

**Comment by tecnomada** [comment]
It was implemented the framework to add buttons with a spinner and it was replaced the custom spinner with the Bootstrap's builtin one.
It was replaced the normal buttons with this new one in 

- Login

- Registration (Test carefully normal registration and with identity providers)

- Banking module

- Confirmation popup

**Comment by luisfpg** [comment]
After a manager reviewed the changeto the new spinner, he preferred the old one.
So we will need to replace the bootstrap spinner to the previously used SVG image in the `<spinner>` component.
For the buttons we will still use Bootstrap's spinner.
Also where the spinner is small (receive QR-code payment) we should use Bootstrap's.
But indeed we should revert to the previous SVG image to the `<spinner>` component. This involves the CSS to invert colors when using the dark theme.
