### ISSUE TITLE
On public registration, the Next button is disabled by several seconds

### ISSUE THREAD

**Issue by tecnomada** [cyclosproject/cyclos4-ui#328]
Talked with Luis.
In the registration form each field is validated when we are typing and if one of that validations is canceled (maybe because other validation was fired) the "requesting" flag used to disable the "Next" button is not false anymore, this is caused due to an Angular's bug: https://github.com/angular/angular/issues/22324
The workaround implemented to avoid the problem mentioned above was a timeout that disable the requesting flag after 20 seconds but this cause the "Next" button to stay disabled even when the field was already validated. Luis found a new workaround in the Angular issue's comment: https://github.com/angular/angular/issues/22324#issuecomment-562401163.
Try to implement the new workaround and in that way the timeout will be removed

Maybe also the delay between typing and validating could be larger to avoid firing too much validations and for some kind of fields (e.g Multi line fields) the validation could be fired when the field get the focus lost (is necessary  to fire a validation in each letter typed in a Description field?)

**Comment by luisfpg** [comment]
Actually, I couldn't find any way to make the request cancellation correctly remove the request from the pending queue.
Instead, I've sidestepped the issue by only validating the first for when the user clicks next.
