### ISSUE TITLE
Login Redirection Issues

### ISSUE THREAD

**Issue by stanfidu** [cyclosproject/cyclos4-ui#33]
@luisfpg @hugovdzee 
Hi,
I installed successfully cyclos-ui locally with cyclos 4.11.5 as backend, It happens that the registration part is Ok on cyclos-ui after verification in the backend. But when a user tried to login, he doen't get redirection to his dashboard page same  situation for admin.
Any help? Please.

**Comment by luisfpg** [comment]
Probably you're missing the part of the link generation script.
See https://github.com/cyclosproject/cyclos4-ui#generating-links-on-the-cyclos-backend-that-point-to-the-frontend

**Comment by stanfidu** [comment]
Thank you for answering in short notice. Well the problem is not with email confirmation indeed I tried that fix with the script but the issue is still persist.
In short, I have a user that already confirm his credential, this process has been made before cyclos-ui installation. After cyclos-ui installation I tried to log in with that user account but I'm still on the guest home page. I verified in the backend, I see the user is connected but there's no dashboard redirection from cyclos-ui.

![CHjG23ttxx](https://user-images.githubusercontent.com/48560205/58272230-0f612a00-7d5c-11e9-94b3-e452a3192a9e.gif)

**Comment by luisfpg** [comment]
I guess it could be a problem with the sending of the cookie that stores part of the session token, as I guess your Cyclos backend is deployed in a sub-path in Tomcat (example: http://localhost:8080/cyclos), while the frontend is at root. After logging in, Cyclos sends a cookie valid for the path "/cyclos", but the frontend is deployed on "/".
This is described in https://github.com/cyclosproject/cyclos4-ui#access-to-the-api-backend
I'll change the application to prevent such issues in development mode.

**Comment by luisfpg** [comment]
That was done in https://github.com/cyclosproject/cyclos4-ui/issues/35. 
Please, let me know if it worked.

**Comment by luisfpg** [comment]
Closing for now. If it happens again, please, reopen.
