### ISSUE TITLE
Add a page to modify the optional agreements and view the agreements logs

### ISSUE THREAD

**Issue by luisfpg** [cyclosproject/cyclos4-ui#341]
This page is needed for user to modify their optional agreements settings

**Comment by agonzalezcy** [comment]
Can not see row detail on Agreement log when click on an not accepted optional agreement row

**Comment by luisfpg** [comment]
The view button is now hidden, as it doesn't make sense to view a no longer accepted agreement text.

**Comment by agonzalezcy** [comment]
UI is different than web. UI only allow see details in log rows where we accepted an agreement
