### ISSUE TITLE
Verify that all pages that manage or view other user's stuff have a reference to it

### ISSUE THREAD

**Issue by tecnomada** [cyclosproject/cyclos4-ui#344]
Like it's done in "Manage user passwords" as admin over a managed user, add a user reference in each page that manage or view other user's stuff.

The search pages have different behaviors, some modify the page tittle with the user name(e.g View advertisements) and other has a reference in the filters (e.g View scheduled payments), take this into account when adding the reference in search pages (maybe could follow the same pattern in all of them).

**Comment by rleonuy** [comment]
Management actions to review with their components:

View <account>
	AccountHistoryComponent

Payment to <account owner>
	PaymentComponent

View scheduled payments
	SearchOwnerInstallmentsComponent

View authorized payments
	SearchTransactionsOverviewComponent

View bought vouchers
	SearchBoughtVouchersComponent

Buy vouchers
	BuyVouchersComponent

View redeemed vouchers
	SearchRedeemedVouchersComponent

Redeem voucher
	RedeemVoucherComponent

Manage passwords
	ManagePasswordsComponent

View identity providers
	UserIdentityProvidersComponent

User status
	ViewUserStatusComponent

User group
	ViewUserGroupComponent

Agreements
	ViewUserAgreementsComponent

View assigned members
	SearchUsersComponent

View brokers
	ListUserBrokersComponent

View operators	
	SearchUserOperatorsComponent

View simple ads
View webshop ads
	UserAdsComponent

View purchases
View sales
	SearchOrdersComponent

View ad interests
	ListAdInterestsComponent

View delivery methods
	ListDeliveryMethodsComponent

View webshop settings
	ViewWebshopSettingsComponent

View <token>
	ListTokenComponent

View documents
	ListDocumentsComponent

View <record>
	SearchRecordsComponent
	TiledRecordsComponent
	ViewRecordComponent
	RecordFormComponent

Run <operation>
	RunOperationComponent
