### ISSUE TITLE
Cannot edit delivery method as user

### ISSUE THREAD

**Issue by tecnomada** [cyclosproject/cyclos4-ui#345]
Delivery methods page has only view mode, there is no button to edit.

**Comment by rleonuy** [comment]
This is because the canEdit canRemove refactor. The API changes were not done in UI yet

**Comment by rleonuy** [comment]
This is because a REST API bug, the canEdit flag is not sent however the deprecated edit flag is sent

**Comment by rleonuy** [comment]
Closing because it's a Cyclos bug see https://jira.cyclos.org/browse/CYCLOS-8170
