### ISSUE TITLE
Day custom field does not consider date format configuration 

### ISSUE THREAD

**Issue by agonzalezcy** [cyclosproject/cyclos4-ui#366]
When use a payment custom field  with a  XS layout, the day format configuration is not taken account

How to reproduce:
1. AdminMenu->System->PaymentFields->add
1.1. Name=PaymentCustomDate
1.2. DataType=Date
2. AdminMenu->System->AccountType->UnitsAccount->TransferTypes->TradeTransferUnits->PaymentFields->AddPaymentField
3. AdminMenu->System->Products->UnitsAccount->VisibleTransactionsFields=Select(PaymentCustomDate)
4. From a mobile access to UI
4.1. asC1->QuickAccess->PayUser
4.1.1. ToUser=c2
4.1.2. PaymentCustomDate=2019-12-30 (It show 12-30-2019 but cufiguration->DateFormat is day/month/year)

**Comment by rleonuy** [comment]
This is a limitation with the native input type date. It uses the format set in the local system.
