### ISSUE TITLE
Manage simple advertisements

### ISSUE THREAD

**Issue by andresmq** [cyclosproject/cyclos4-ui#38]

**Comment by rleonuy** [comment]
CRUD (owner/management)
	- advertisement -> done
View
	- simple fields -> done	
	- actions
 		* edit -> done
		* remove -> done
		* print -> done
		* custom operations -> done
		* hide / unhide -> done
		* submit for authorization -> done
		* set as draft -> done
		* approve (management) -> done
		* reject (management) -> done		

Search 
	- general -> done
	- owner -> done
	- management -> done

Questions
	- ask -> done
	- remove -> done
