### ISSUE TITLE
Script Failing after updating from version 4.12 to 4.14 (PaymentService)

### ISSUE THREAD

**Issue by EdwinM96** [cyclosproject/cyclos4-ui#406]
I have a script that fails after the update. 

The part where it is failing is when commiting a transaction through the paymentService available on the scripting module. 

The method I am calling is paymentService.perform(PerformPaymentDTO) and the data I am adding to the DTO is previously validated. In the DTO this is the data I am adding:
- The "from" user is correct.
- The "to" is an admin.
- The transaction type is correct, which is an available transaction between the "from" user and admin.
- The "amount" is a lot lower than the available balance the "from" user has.

The perform method is just returning a null cause CyclosException. I have not being able to find what the problem is due to there not being an specified cause on the throwed error.

**Comment by luisfpg** [comment]
This repository is solely for cyclos4-ui related issues.
For general Cyclos support, please, use our [forum](https://forum.cyclos.org/).

**Comment by luisfpg** [comment]
Anyway, @EdwinM96,  when reporting on the forum, please, be more specific:

> I have a script that fails after the update.
Update from which version and to which version?

> The "to" is an admin.
Administrators don't have an account. Please, use SystemAccountOwner instead.

> The perform method is just returning a null cause CyclosException
Please, attach the error stack trace in the forum post.
