### ISSUE TITLE
Account Information (Balance) not visible on profile page in the new frontend

### ISSUE THREAD

**Issue by cccceee** [cyclosproject/cyclos4-ui#407]
Hi, I need to display each user's account balance on their profile page so that it's visible for all users. I enabled the option to display the fields and assigned the product to my groupset. The balance shows up correctly in profile page using the classic frontend but is not visible in the new frontend.

Below are screenshots for the same logged-in user profile with no changes in configuration:

Classic frontend:
![image](https://user-images.githubusercontent.com/75965163/102042774-86ee2280-3df4-11eb-98e2-dd895a4d9d4b.png)

New frontend:
![image](https://user-images.githubusercontent.com/75965163/102041668-e3037780-3df1-11eb-8772-91a503e91c11.png)

Any help would be greatly appreciated. Thanks!

**Comment by luisfpg** [comment]
Thanks for the report.
Will likely being included in 4.14.2.

**Comment by cccceee** [comment]
Thanks. Is there a simple way to show balance as a custom profile field? I am only interested in the "balance" value, not account activity.

**Comment by luisfpg** [comment]
Unfortunately, not. At least no easy way. It is technically possible with scripts, by using a service interceptor script to replace a custom field value.

**Comment by luisfpg** [comment]
This issue couldn't make it into 4.14.2. It has been rescheduled for 4.14.3.
