### ISSUE TITLE
Users filter is shown as admin filter on new UI

### ISSUE THREAD

**Issue by AurelienBISOTTI** [cyclosproject/cyclos4-ui#408]
I have an issue with the filter : when connected as a pro (user), when searching the catalog, I have the admin options in the filter.

On the old UI, I have just 2 options in the filter

![Clipboard - 19 février 2021 15 35](https://user-images.githubusercontent.com/12530585/109132351-0a60b400-7754-11eb-8a21-33c8c15c0014.png)
![Clipboard - 19 février 2021 15 38](https://user-images.githubusercontent.com/12530585/109132354-0b91e100-7754-11eb-8eab-63e61063d7ff.png)

**Comment by luisfpg** [comment]
This was already fixed and will be released with 4.14.5, which should be published this week.
