### ISSUE TITLE
How to include the footer in new frontend?

### ISSUE THREAD

**Issue by RajeshRP** [cyclosproject/cyclos4-ui#419]
Please can anyone help with how to add the footer that appears on all Guest's page. Noticed top-bar for the top navigation but nothing like footer component or so. How to proceed please? Should we create a custom component and include it in UIComponent html, or is there any other workaround from the backend?

**Comment by luisfpg** [comment]
There's no standard footer.
The guest page has a footer as part of its content.
To have a footer across all pages, you should create a footer component as you mentioned.

**Comment by RajeshRP** [comment]
What if there are many guest pages, the footer has to be copy pasted across those page's content? when there is a header/top bar given separately for new fontend, why not footer? The component can be created in the code, but what if the content needs to come from the backend? Please suggest.

**Comment by luisfpg** [comment]
I understand it is a reasonable request.
I'll pass it on to the management, so maybe this will be included in 4.15.

**Comment by RajeshRP** [comment]
It will also be good if there is any option to create a shared content, that can be included wherever (other pages, between the contest of any other page) required.

**Comment by luisfpg** [comment]
Actually what was defined is to have another entry in `Content management > Static content` which is the new frontend footer.

**Comment by RajeshRP** [comment]
> Actually what was defined is to have another entry in `Content management > Static content` which is the new frontend footer.

Understood this. Thanks.




> It will also be good if there is any option to create a shared content, that can be included wherever (other pages, between the contest of any other page) required.

This could be new feature request to define a shareable content, that can be included within other content.

**Comment by luisfpg** [comment]
> This could be new feature request to define a shareable content, that can be included within other content.

Can you elaborate on this? Which other content would benefit from a shareable content? Would this shareable content be a separated entity, defined elsewhere?

**Comment by RajeshRP** [comment]
Let's say for e.g., there should be warning/info content that should appear in the middle of every page (i.e., every menu item's page). So instead of copy pasting the content in every single page, it would be nice if I could define the content as shareable, and then insert while editing the other page. If the warning/info content needs to be changed it is a one time task rather than editing all those pages.

May be while creating content, there is a flag to state that it is shareable, and while creating other page content, it can be inserted. 

Am not sure how feasible is this, but just an idea. Thanks for your time.
