### ISSUE TITLE
Application translation fails

### ISSUE THREAD

**Issue by AureliusHogan** [cyclosproject/cyclos4-ui#430]
With a blank installation of 4.15 hosted separately from Cyclos it seems like the translations are not displayed correctly. This screenshot shows the user profile in German:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/30202934/169495306-e8ad5faf-514a-4916-83e2-4cf395233378.png">

When I look at i18n.de.json there is a translation for id _user.registrationDate_ and should show "Registrierungsdatum" instead of "Registration date". Same with id _user.name_ or _user.username_ etc.

A french screenshot shows the correct values for _user.name_ and _user.username_ but not for _user.registrationDate_:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/30202934/169497153-07b0507c-a180-4486-8550-46532b236154.png">

Have you got the same effect or is this a problem of my installation?

**Comment by andresmq** [comment]
Hi @AureliusHogan,

To make the German translation work, you can edit the 
ng-translation-gen.json file and add "de" to the "locales" array property.
We'll include a fix for it in version 4.15.7.

The problem with the "registration date" shown in English, is that there is no French translation for that key, and then English is used.

Remember that you can run 'npm run merge-translations' to include the defaults (in English) in your i18n JSON translation file for all of those lacking a translation.

Regards.
