### ISSUE TITLE
index has hardcoded spinner 

### ISSUE THREAD

**Issue by aidan729** [cyclosproject/cyclos4-ui#441]
I have already set up a docker container for this UI however the main index is hardcoded with a "rootSpinner"
how is this supposed to be a ui based application set up with no programability required if the main index is hardcoded
with a "rootSpinner" seems a bit redundant to me..

**Comment by luisfpg** [comment]
I didn't get your point. It is hardcoded in the index because it takes some time before all the Angular app is loaded and ready.
