### ISSUE TITLE
Incorrect file reference in the tsconfig.pay.json file

### ISSUE THREAD

**Issue by anantanandgupta** [cyclosproject/cyclos4-ui#445]
I have just downloaded the latest source code for customization and found that there are some issues presented by the typescript 

https://github.com/cyclosproject/cyclos4-ui/blob/107e7991babdeaf1b0238cac17658b3b5acc9dea/src/tsconfig.pay.json#L8

![image](https://user-images.githubusercontent.com/3868003/227948367-6a019a4c-198e-4696-9722-eac5b0015cee.png)

though it is not hiddering the build process, but since the pay folder is no existent in the project it can be removed along with the respective references to the file.

**Comment by luisfpg** [comment]
Thanks for the report.
The idea was to have the /pay (tickets and easy invoice) migrated to this project, but we couldn't do it yet.
Will likely be done in 4.17.
This will be fixed in the final 4.16.
