### ISSUE TITLE
Third party SSO/Third party user authentication (using something like Kerberos)

### ISSUE THREAD

**Issue by JasoonS** [cyclosproject/cyclos4-ui#5]
I couldn't find any docs related to this feature. Could you please point me to them?

I saw this feature was added in version Cyclos 4.7 as per this article: https://www.cyclos.org/newsletter/2016_10/index.html

Many thanks!

**Comment by luisfpg** [comment]
You have to enable CORS.
On `cyclos.properties`, set the `cyclos.cors.origin` to either `*` to anable any address to connect (not recommended for production) or to the URL where the application is deployed.
Keep in mind that this `cyclos4-ui` still very experimental, and subject to drastically change until we have a proper release.

**Comment by JasoonS** [comment]
Hi, thanks for the answer. How do you set the `cyclos.properties`? I have been running cyclos from the docker containers that you provide.

**Comment by luisfpg** [comment]
The easiest way is to override a property via a JVM argument, which can be set as the JAVA_OPTS environment variable.
Here's an example for starting the container similar to the example on https://hub.docker.com/r/cyclos/cyclos/:
```bash
docker run -d \
    --name=example-app \
    -p 80:8080 \
    --net=example-net \
    -e DB_HOST=example-db \
    -e DB_NAME=example \
    -e DB_USER=example \
    -e DB_PASSWORD=examplepwd \
    -e JAVA_OPTS="-Dcyclos.cors.origin=*" \
    cyclos/cyclos
```
You can override any property like that.

**Comment by Wisdom0063** [comment]
@luisfpg How do I override multiple settings. I want to override cyclos.header.remoteAddress and cyclos.header.protocol

**Comment by luisfpg** [comment]
```bash
docker run -d \
    --name=example-app \
    -p 80:8080 \
    --net=example-net \
    -e DB_HOST=example-db \
    -e DB_NAME=example \
    -e DB_USER=example \
    -e DB_PASSWORD=examplepwd \
    -e JAVA_OPTS="-Dcyclos.cors.origin=* -Dcyclos.header.remoteAddress=X-Forwarded-For -Dcyclos.header.protocol=X-Forwarded-Proto" \
    cyclos/cyclos
```

**Comment by Wisdom0063** [comment]
@luisfpg  Thanks very much
