### ISSUE TITLE
Footer Links to Cyclos Pages

### ISSUE THREAD

**Issue by atitokor** [cyclosproject/cyclos4-ui#56]
1. I'm trying to fetch Cyclos pages created in Content > Menu and pages with links on the Footer. In order to keep the Information menu trim, these pages links/menu tems will not appear under Information. I'm not really sure how to do this or if it's possible.
![1](https://user-images.githubusercontent.com/12918740/58645486-168eb780-82c9-11e9-9f1b-7a7b5e7c9cf3.png)

2. There are a number of floating pages I wish to create in Cyclos that can only be called by a link on another page. They will neither appear on the top menu bar nor in the Footer area. Is this possible? How can I do this? This example is a link on the Careers page that opens a page with Job listings, or goes to a jobs search form or browsing page.
![2](https://user-images.githubusercontent.com/12918740/58646890-fb717700-82cb-11e9-9978-0b512f40808f.png)

Thanks in advance.
Art

**Comment by luisfpg** [comment]
We currently don't support pages which are not in the Menu.
