### ISSUE TITLE
Web Access stuck at loading screen

### ISSUE THREAD

**Issue by bingy92** [cyclosproject/cyclos4-ui#6]
I only get loading circle

**Comment by luisfpg** [comment]
Did you follow the README instructions?
Set the Cyclos backend URL in configuration.ts and used `npm start`?
There's a live version on https://test-ui.cyclos.org/, updated directly from github, just setting some custom configuration.

**Comment by bingy92** [comment]
Thanks for your reply,

Yes I did. Followed all the steps. I had it installed and working before but now it doesn't work when I tried to install it again.

I tried installing on Ubuntu 16/18 as well as Centos7 and got same result. One thing I did notice was when i installed the nodejs it came with npm6+ . I even tried downgrading to npm5+ but got same result.

Any ideas?

**Comment by bingy92** [comment]
I just looked at the https://test-ui.cyclos.org/. looks impressive.

Do you have a demo login I use use to look around?

**Comment by luisfpg** [comment]
Closing for the lack of feedback
