### ISSUE TITLE
Various

### ISSUE THREAD

**Issue by atitokor** [cyclosproject/cyclos4-ui#63]
1. I'm missing the "Users" menu in frontend.

![1](https://user-images.githubusercontent.com/12918740/58747680-1bbc4580-8434-11e9-84bc-84dd3d5710dd.png)

2. I'm missing in Frontend certain functions relating to Operators (Users > Operators > Groups; Users > Operators _ Operators; Users > Operators > Connected Operators)

![2](https://user-images.githubusercontent.com/12918740/58747796-bc5f3500-8435-11e9-94c0-bd4b30ffbad0.png)

3. I'm missing "Place webshop ad" function in Frontend. Didn't test for simple ads.

![3](https://user-images.githubusercontent.com/12918740/58747941-9044b380-8437-11e9-8862-661e547722a3.png)

![4](https://user-images.githubusercontent.com/12918740/58747944-9aff4880-8437-11e9-8797-aaa08467631e.png)

Any help to resolve these will be highly appreciated. Thanks in advance.

Art

**Comment by luisfpg** [comment]
The funcionality in this new front end is being implemented yet.
See https://github.com/cyclosproject/cyclos4-ui#implemented-functionality
The users search is in the marketplace menu, as for most systems, searching users is searching where to spend.

**Comment by atitokor** [comment]
Hi @luisfpg 

Thanks for the update. We do see that items 58, 59 and 60 do bear some resemblance to adding operators.

Just to help me understand, did you mean "Place webshop ad" is yet to be implemented in the new frontend? If so could we request it for v1.1, or is it already on 1.1 version todo list?

Also do we need to wait for 1.1 to show the Users menu for logged-in users? If it can be added now how can we do that?

Thanks
Art

**Comment by luisfpg** [comment]
The connected users is tracked in #50.
Placing webshop ads is still to be implemented.
You can negotiate the priorization of features by contacting sales@cyclos.org.
