### ISSUE TITLE
Edit Profile Not Saving

### ISSUE THREAD

**Issue by atitokor** [cyclosproject/cyclos4-ui#64]
I just edited my end-user profile, and though the process completed smoothly, the change was not saved.

![1](https://user-images.githubusercontent.com/12918740/58748195-6fca2880-843a-11e9-8be6-4950dd66c9f1.png)

Thanks
Art

**Comment by luisfpg** [comment]
@atitokor I couldn't reproduce it... Saving the profile works as expected.
What exactly isn't working?

**Comment by luisfpg** [comment]
Closing this, as we cannot reproduce.
