### ISSUE TITLE
Loading screen when trying to register an user as admin or public registration

### ISSUE THREAD

**Issue by rleonuy** [cyclosproject/cyclos4-ui#82]
The page stays at loading screen. See image:
![error](https://user-images.githubusercontent.com/50959077/59353217-d7189000-8cf8-11e9-8eb6-cb92430ae7ba.png)

Also (after fix the loading issue) check when the registration group does not have any fields to be entered it produces an UnexpectedDataAccessException

**Comment by rleonuy** [comment]
Still have the unexpected data access error. And the notification error appears twice (above each other)

![step1](https://user-images.githubusercontent.com/50959077/59374042-5326ce00-8d21-11e9-8bef-f75954f61b89.png)
![step2](https://user-images.githubusercontent.com/50959077/59374048-5457fb00-8d21-11e9-9b35-dff1f18c68c0.png)
![step3](https://user-images.githubusercontent.com/50959077/59374051-5621be80-8d21-11e9-88ad-6bed7b04a99d.png)
![error](https://user-images.githubusercontent.com/50959077/59374053-57eb8200-8d21-11e9-8aab-2fc5f04f0496.png)

**Comment by luisfpg** [comment]
The server-side error happens when full name field is disabled - fixed in 4.12.1.
The client error is fixed.
