### ISSUE TITLE
White space in date picker (custom field date)

### ISSUE THREAD

**Issue by rleonuy** [cyclosproject/cyclos4-ui#85]
When opening a date picker from a custom field there is a white space
![error](https://user-images.githubusercontent.com/50959077/59373142-6e90d980-8d1f-11e9-9e7c-72682a9459c9.png)

**Comment by rleonuy** [comment]
Also: the red cross position can be improved when the date field is required 
![error2](https://user-images.githubusercontent.com/50959077/59373527-3c33ac00-8d20-11e9-8e10-e56ddd7be083.png)

**Comment by luisfpg** [comment]
Couldn't fix the cross position when invalid, as it is managed by some obscure bootstrap styles...
