### ISSUE TITLE
Captcha not working at public registration / forgot password

### ISSUE THREAD

**Issue by rleonuy** [cyclosproject/cyclos4-ui#87]
Captcha image does not appear

![error](https://user-images.githubusercontent.com/50959077/59374267-d811e780-8d21-11e9-87f5-39b3294f30ac.png)

**Comment by rmvanarkel** [comment]
It seems still not working in forgot password in firefox. In Chrome all works perfect!

**Comment by luisfpg** [comment]
Fixed with #213
