### ISSUE TITLE
Advertisement categories only support two levels

### ISSUE THREAD

**Issue by rleonuy** [cyclosproject/cyclos4-ui#88]
At main web or mobile app it allows to search up to 4 category levels
![error1](https://user-images.githubusercontent.com/50959077/59374578-8c137280-8d22-11e9-9c35-50569a160b88.png)
![error2](https://user-images.githubusercontent.com/50959077/59374579-8c137280-8d22-11e9-9ef5-d24dbc6e4ca6.png)

**Comment by luisfpg** [comment]
This was by design in the new frontend.
We would only probably do something different if some customer demands.
